import '../globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div>
        <div className="navBar2">
            <Link href="/cart">장바구니</Link>
            <Link href="/cart/payment">결제페이지</Link>
        </div>
        <p>현대카드 무이자 이벤트 중</p>
        {children}
    </div>

  )
}
